import turtle

#draw red rectangle
draw=turtle.Turtle()
draw.speed(0)
draw.pensize(3)
draw.color('black','red')
draw.up()
draw.goto(-300,250)
draw.down()
draw.begin_fill()
draw.forward(600)
draw.right(90)
draw.forward(120)
draw.right(90)
draw.forward(600)
draw.right(90)
draw.forward(120)
draw.end_fill()

#draw yellow rectangle
draw.backward(120)
draw.color('black','yellow')
draw.begin_fill()
draw.backward(120)
draw.right(90)
draw.forward(600)
draw.left(90)
draw.forward(120)
draw.end_fill()


#draw green rectangle
draw.backward(120)
draw.color('black','green')
draw.begin_fill()
draw.backward(120)
draw.right(90)
draw.backward(600)
draw.right(90)
draw.backward(120)
draw.end_fill()
draw.hideturtle()

#draw black star
draw.up()
draw.goto(0,118)
draw.down()
draw.showturtle()
draw.color('black','black')
draw.left(35)
draw.up()
draw.forward(14)
draw.down()
draw.begin_fill()
draw.forward(106)
draw.right(150)
draw.forward(145)
draw.right(155)
draw.forward(150)
draw.right(155)
draw.forward(145)
draw.right(145)
draw.forward(103)
draw.hideturtle()
draw.end_fill()

#Caption Flag
draw.up()
draw.goto(0,-200)
draw.down()
draw.write('God Bless My Homeland',align='center',font=('Courier',20,'normal'))
draw.up()
draw.goto(0,-260)
draw.down()
draw.write('\nG H A N A',align='center',font=('Arial',20,'bold'))
turtle.done()